server:
  AppVersion: 1.0.0
  Port: 8080
  PprofPort: 8080
  Mode: production
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false
  MaxConnectionIdle: 5
  Timeout: 15
  MaxConnectionAge: 5
  Time: 120
  ShutdownTimeout: 3
  Url: http://localhost:8080
  NameService: BackendTestAPI

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

JWT:
  SecretKey: az1D4ljDi4zSkfsmishqOUH!30*
  AccessTokenSecret: oY0p7Mwa3WzDk027yBSvm330@!
  RefreshTokenSecret: lW8qOyQby9ISPZGRPg6c8zIXoYoI