name: CI From Github Actions For Frontend and Backend Service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend Docker
        uses: docker/build-push-action@v2
        with:
          context: ./simple-fe
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          
      - name: Build and Push Backend Docker
        uses: docker/build-push-action@v2
        with:
          context: ./backend-api-test
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Start containers with docker-compose
        run: docker-compose up -d

      - name: Wait for services on container to be ready
        run: sleep 10

      - name: Test backend connection
        run: |
          curl --fail http://localhost:8080 || exit 1

      - name: Test frontend connection
        run: |
          curl --fail http://localhost:3000 || exit 1